on: pull_request
permissions:
    contents: read
    pull-requests: write
jobs:
    find-comment-and-update:
        runs-on: ubuntu-latest
        name: 'Find comment and update'
        steps:
          - name: Checkout Target Branch
            uses: actions/checkout@v4
            with:
                ref: ${{ github.base_ref }}
          - name: Run script on target branch 
            run: npm run generate:target
          - name: Checkout PR Branch
            uses: actions/checkout@v4
            with:
                ref: ${{ github.ref }}
          - name: Run script on PR branch
            run: npm run generate:pr
          - name: Output directory contents
            run: ls
          - name: Update PR with test results
            uses: edumserrano/find-create-or-update-comment@v2
            with:
                issue-number: ${{ github.event.pull_request.number }}
                body-includes: '<!-- breaking-change-detector-comment -->'
                comment-author: 'github-actions[bot]'
                body: |
                    <!-- breaking-change-detector-comment -->
                    My awesome comment updated
                edit-mode: replace

