on: pull_request
permissions:
    pull-requests: write
jobs:
    find-comment-and-update:
        runs-on: ubuntu-latest
        name: 'Find comment and update'
        steps:
          - name: Update PR with test results
            uses: edumserrano/find-create-or-update-comment@v2
            with:
                issue-number: ${{ github.event.pull_request.number }}
                body-includes: '<!-- some-unique-id -->'
                comment-author: 'github-actions[bot]'
                body: |
                    <!-- some-unique-id -->
                    My awesome comment
                edit-mode: replace

