name: Comment
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    issue_comment:
        types: [created]
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '###secretkey')}}
    runs-on: ubuntu-latest
    steps:
          - run: |
              echo A comment on PR $NUMBER
            env:
              NUMBER: ${{ github.event.issue.number }}
          - run: |
              echo ${{ github.event.comment.body }}
          - run: |
              echo ${{ github.event.issue.pull_request }}
