name: Versioning
on: 
    workflow_dispatch:
jobs:
    checkout: 
        name: Checkout
        runs-on: windows-2019
        outputs:
            tag: ${{env.tag}}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup node
                uses: actions/setup-node@v3
                with:
                    node-version: 20
            -   name: Set git user
                run: |
                    git config --global user.email "kinnaird.matthew@gmail.com"
                    git config --global user.name "CICD User"
            -   name: Bump
                # shell: cmd
                run: |
                    $TAG=$(npm version patch)
                    $env:GITHUB_ENV="tag=$TAG"
                    echo "${{env.tag}}"
    
    debug: 
        name: Debug
        runs-on: windows-2019
        needs: checkout
        steps: 
            -   name: Echo variables
                run: |
                    echo ${{needs.checkout.outputs.tag}}
                    echo "${{needs.checkout.outputs.tag}}"