name: Versioning
on: 
    workflow_dispatch:
jobs:
    checkout: 
        name: Checkout
        runs-on: windows-2019
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup node
                uses: actions/setup-node@v3
                with:
                    node-version: 20
            -   name: Set git user
                run: |
                    git config --global user.email "kinnaird.matthew@gmail.com"
                    git config --global user.name "CICD User"
            -   name: Bump
                # shell: cmd
                run: |
                    $VERSION=$(npm version patch)
                    echo "VERSION=$VERSION" >> $GITHUB_ENV
                    echo ${{env.version}}